設計
brokenManager/haracho-go pull request #1
Opened 2020-04-09 13:18 UTC by mirror-kt

設計しました(さいなさんがほとんどやったやんけ)

internal/cmd以下にコマンドのファイルおいてください
```golang
func init() {
    help := client.HelpContext { // いい感じに
    }
    service.GetCommandCollection().AddCommand(&help, "コマンド名", func(arg *client.Arg, ctx client.CommandContext) {
        // コマンドの処理
    })
}
```
です

2020-04-09 15:41 UTC, kawaemon requested changes

2020-04-09 15:41 UTC, kawaemon commented on internal/client/argument.go
> +}
IsSameだと意味がわかりにくいから、`IsSameCommand`とかのほうがいいかも？

2020-04-09 15:41 UTC, kawaemon commented on internal/client/command.go
> +	arg       string
このargは何を格納するものですか？

2020-04-09 15:41 UTC, kawaemon commented on internal/client/discord/discord_context.go
> +type Context struct {
名前、CommandContextとかのほうがいいかも？

2020-04-09 15:41 UTC, kawaemon commented on internal/client/console/console_client.go
> +	_ "haracho-go/internal/command"
必要ない気が

2020-04-09 15:41 UTC, kawaemon commented on internal/client/command_collection.go
> +func (c *CommandCollection) AddSubCommand(help *HelpContext, arg string, subCommands []CommandExecutable) {
`AddSubCommands`のほうがいいかも

2020-04-09 15:41 UTC, kawaemon commented on internal/client/command.go
> +func (c command) execute(arg *Arg, ctx CommandContext) {
レシーバーがここだけ値レシーバーなのは何故

2020-04-09 15:43 UTC, mirror-kt commented on internal/client/command.go
> +	arg       string
コマンド名(!ping)など
commandNameとかの方がいいかな？

2020-04-09 15:44 UTC, mirror-kt commented on internal/client/console/console_client.go
> +	_ "haracho-go/internal/command"
init()でコマンドを登録しているので必要
```golang
func init() {
}
```
は各パッケージに複数存在できる特別な関数でパッケージの初期化に使われる。
import時に呼ばれるからimportが必須。

2020-04-09 15:45 UTC, mirror-kt commented on internal/client/command.go
> +func (c command) execute(arg *Arg, ctx CommandContext) {
インターフェイス(`CommandExecutable`)を実装するため

2020-04-09 15:45 UTC, kawaemon commented on internal/client/command.go
> +	arg       string
のほうがいいと思います。HelpContextに持たせとくのでもいいと思いますが...

2020-04-09 15:47 UTC, mirror-kt commented on internal/client/argument.go
> +}
Equalsとかもありではあるけど
どうしようか

2020-04-09 15:50 UTC, kawaemon commented on internal/client/console/console_client.go
> +	_ "haracho-go/internal/command"
あー、、、意図がわかりにくいので、initじゃなく別の方法を使う（登録するための関数を別で用意するとか）か、コメントで書いといたほうがいいかも。。。

2020-04-09 15:52 UTC, kawaemon requested changes

2020-04-09 15:52 UTC, kawaemon commented on cmd/console_client.go
> +func main() {
cmdパッケージに複数のmain関数があります。パッケージを分けてください。

2020-04-09 15:58 UTC, kawaemon commented on internal/client/argument.go
> +}
EqualsだとArgインスタンス同士が等価か比較してるように思ってしまうので...

2020-04-09 16:02 UTC, kawaemon commented on internal/client/command.go
> +func (c command) execute(arg *Arg, ctx CommandContext) {
ポインタの状態で持てばCommandExecutableを実装するので、CommandCollection structの`commands []CommandExecutable`を`commands []*CommandExecutable`にすればいいと思います

2020-04-09 16:07 UTC, kawaemon commented on internal/client/command.go
> +func (c command) execute(arg *Arg, ctx CommandContext) {
修正です。`[]CommandExecutable`はそのままにして、AddCommand関数と、AddSubCommand関数で作るCommandインスタンスをポインタで保持すればOKです。

2020-04-09 16:34 UTC, kawaemon commented
*** †APPROVE† ***

2020-04-09 16:35 UTC, kawaemon approved these changes
***†APPROVE†***

2020-04-10 02:51 UTC, MikuroXina requested changes
レ　ビ　ュ　ー　オ　ワ　タ

2020-04-10 02:51 UTC, MikuroXina commented on internal/client/argument.go
> +}
```suggestion
import "strings"

type Arg struct {
	commandName string
	args        []string
}

func NewArg(message string) *Arg {
	split := strings.Split(message, " ")
	return &Arg {
		commandName: split[0],
		args: split[1:],
	}
}
```

フィールドは非公開にして、文字列から `Arg` を作る手段だけを提供するべき
他のレシーバとかも同様に直してね

2020-04-10 02:51 UTC, MikuroXina commented on internal/command/ping_pong/ping_pong_command.go
> +package ping_pong
```suggestion
package pingpong
```
パッケージ名に `_` はあまり入れないでほしい
あわせてディレクトリ名も直してね

2020-04-10 02:51 UTC, MikuroXina commented on internal/command/ping_pong/ping_pong_command.go
> +}
```suggestion
func Build(collection *client.CommandCollection) {
	help := client.HelpContext{
		Name:            "!ping",
		Description:     "PingPong",
		ArgsDescription: nil,
	}

	collection.AddCommand(&help, "!ping", func(arg *client.Arg, ctx client.CommandContext) {
		ctx.SendMessage("pong!")
	})
}
```
`CommandCollection` を受け取って書き加えるだけにするべき

2020-04-10 02:51 UTC, MikuroXina commented on internal/command/ping_pong/ping_pong_command.go
> +	"haracho-go/internal/service"
```suggestion
```
`service` に依存してるのはおかしい

2020-04-10 02:51 UTC, MikuroXina commented on internal/command/register_commands.go
> +}
```suggestion
import (
	"haracho-go/internal/client"
	"haracho-go/internal/command/pingpong"
)

func RegisterCommands(collection *client.CommandCollection) {
	pingpong.Build(collection)
}
```
`CommandCollection` を受け取って書き加えるだけにするべき

2020-04-10 02:51 UTC, MikuroXina commented on internal/client/console/console_client.go
> +	return &client.Arg{CommandName: split[0], Args: split[1:]}, CommandContext{}
```suggestion
	return client.NewArg(input), CommandContext{}
```
別記の通りに `Arg` を直すとこうなる

2020-04-10 02:51 UTC, MikuroXina commented on internal/client/discord/discord_parser.go
> +	return &client.Arg{CommandName: split[0], Args: split[1:]}, p.ctx
```suggestion
	return client.NewArg(p.rawMessage), p.ctx
```
別記の通りに `Arg` を直すとこうなる

2020-04-10 02:51 UTC, MikuroXina commented on internal/client/discord/discord_parser.go
> +	"strings"
```suggestion
```
いらない

2020-04-10 02:51 UTC, MikuroXina commented on internal/client/console/console_client.go
> +	"strings"
```suggestion
```
いらない

2020-04-10 02:51 UTC, MikuroXina commented on cmd/console_client/main.go
> +	command.RegisterCommands()
```suggestion
	collection := new(client.CommandCollection)
	command.RegisterCommands(collection)
```
別記の通りに `RegisterCommands` を直すとこうなる

2020-04-10 02:51 UTC, MikuroXina commented on cmd/console_client/main.go
> +		client.ExecuteCommand(c, service.GetCommandCollection())
```suggestion
		client.ExecuteCommand(c, collection)
```
上記の続き

2020-04-10 02:51 UTC, MikuroXina commented on cmd/console_client/main.go
> +	"haracho-go/internal/service"
```suggestion
```
いらない

2020-04-10 02:51 UTC, MikuroXina commented on internal/service/command_service.go
> +}
```suggestion
```
後々のことを考えるとこのシングルトンはかなり悪手

2020-04-10 02:51 UTC, MikuroXina commented on cmd/console_client/main.go
> +	for i := 0; i < 5; i++ {
なんで五回ループしてるの
(一度 `CommandCollection` を `execute` したら中身は全部実行されるしよく分からない)

2020-04-10 02:51 UTC, MikuroXina commented on cmd/discord_client/main.go
> +	c := discord.Client{Token: os.Getenv("TOKEN")}
```suggestion
	collection := new(client.CommandCollection)
	command.RegisterCommands(collection)

	c := discord.Client{Token: os.Getenv("TOKEN"), Collection: collection}
```
別記の通りに `RegisterCommands` を直すとこうなる
`import` も追加してね

2020-04-10 02:51 UTC, MikuroXina commented on internal/client/discord/discord_client.go
> +}
```suggestion
type Client struct {
	Token      string
	session    *discordgo.Sessionc
	Collection *client.CommandCollection
}
```
`CommandCollection` を外部から入れてもらう方が制御が効く

2020-04-10 02:51 UTC, MikuroXina commented on internal/client/discord/discord_client.go
> +		client.ExecuteCommand(parser, service.GetCommandCollection())
```suggestion
		client.ExecuteCommand(parser, c.Collection)
```
上記にあわせるとこうなる

2020-04-10 02:51 UTC, MikuroXina commented on internal/client/sub_command.go
> +	return arg.Next().IsSameCommand(c.arg)
なんで次の引数と自分の名前 (第 0 引数) を比較しているのか分からない
(自分の勘違いかもしれないので変更の提案はやめとく)

2020-04-10 02:51 UTC, MikuroXina commented on internal/logger/logger.go
> +type Logger interface {
これ使われてないと思う

2020-04-10 03:54 UTC, MikuroXina requested changes
これ要らなくなるので追加

2020-04-10 03:54 UTC, MikuroXina commented on internal/client/console/console_client.go
> +	_ "haracho-go/internal/command"
```suggestion
	_ "haracho-go/internal/command"
```
いらない

2020-04-10 04:07 UTC, MikuroXina requested changes
実際に動かしてて動かなかったので追記

2020-04-10 04:07 UTC, MikuroXina commented on internal/client/discord/discord_client.go
> +var l = logger.BasicLogger{Logger: &log.Logger{}}
```suggestion
var l = logger.BasicLogger{
	Logger: log.New(os.Stdout, "DiscordClient: ", log.LstdFlags),
}
```
初期化の仕方がおかしい

2020-04-10 04:08 UTC, MikuroXina commented on internal/client/argument.go
> +}
他のファイルからアクセスできるのもおかしいので、`Arg` 用の `package` を作ってもいいかもしれない

2020-04-10 12:49 UTC, mirror-kt commented on cmd/console_client/main.go
> +	for i := 0; i < 5; i++ {
特に意味はない
無限ループにして起動しっぱなしにしたら怒られたので

2020-04-10 12:49 UTC, mirror-kt commented on cmd/console_client/main.go
> +	for i := 0; i < 5; i++ {
1回にしときます

2020-04-10 12:51 UTC, mirror-kt commented on internal/client/sub_command.go
> +	return arg.Next().IsSameCommand(c.arg)
これはミスですね
IsSameCommandは今の引数と比べた上でexecuteで次の引数を渡すべきでした

2020-04-10 13:06 UTC, MikuroXina approved these changes
たぶん動くと思うから *Approve* しようぜ

2020-04-10 13:07 UTC, mirror-kt commented
Mergeしまーす

2020-04-10 13:07 UTC, merged